// SPDX-License-Identifier: AGPL-3.0-only
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('event workspace connects a custom type, meeting, preparation, attendance, documents and calendar', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore demo workspace' }).click();
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();
  await page.goto('/#/events');
  await expect(page.getByRole('heading', { name: 'Events & collaboration', exact: true })).toBeVisible();
  const token = String(Date.now()); const title = `Community briefing ${token}`; const typeName = `Workshop ${token}`;
  const state = await (await page.request.get('/api/state')).json();
  const volunteer = state.volunteers.find((item: { status: string }) => item.status === 'active');
  const shift = state.shifts[0];
  await page.getByRole('button', { name: 'Event types', exact: true }).click();
  await page.getByLabel('Type name', { exact: true }).fill(typeName);
  await page.getByLabel('Type description', { exact: true }).fill('Community orientation with an online briefing.');
  await page.getByRole('checkbox', { name: 'Online meeting', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Preparation checklist', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Attendance', exact: true }).check();
  await page.getByRole('button', { name: 'Save event type', exact: true }).click();
  await expect(page.getByRole('button', { name: new RegExp(typeName) })).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'New event', exact: true }).click();
  await page.getByLabel('Event title', { exact: true }).fill(title);
  await page.getByLabel('Event type', { exact: true }).selectOption({ label: typeName });
  await page.getByLabel('Event status', { exact: true }).selectOption('confirmed');
  await page.getByLabel('Description', { exact: true }).fill('Welcome briefing and practical preparation for new volunteers.');
  await page.getByLabel('Meeting platform', { exact: true }).selectOption('zoom');
  await page.getByLabel('Meeting link', { exact: true }).fill('https://example.org/meeting/briefing');
  await page.getByLabel('Meeting agenda', { exact: true }).fill('Introductions, station arrangements, questions.');
  await page.locator('summary').filter({ hasText: 'Participants' }).click();
  await page.getByRole('checkbox', { name: new RegExp(volunteer.name) }).check();
  await page.locator('summary').filter({ hasText: 'Service shifts' }).click();
  await page.getByRole('checkbox', { name: new RegExp(shift.title) }).first().check();
  await page.getByRole('button', { name: 'Create event', exact: true }).click();
  await expect(page.getByRole('dialog', { name: title, exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Meeting', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Join meeting', exact: false })).toHaveAttribute('href', 'https://example.org/meeting/briefing');
  await expect(page.getByText('Introductions, station arrangements, questions.', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Checklist', exact: true }).click();
  await page.getByLabel('Preparation item', { exact: true }).fill('Prepare the welcome pack');
  await page.getByLabel('Item owner', { exact: true }).fill('Coordination team');
  await page.getByRole('button', { name: 'Add preparation item', exact: true }).click();
  await page.getByRole('checkbox', { name: /Prepare the welcome pack/ }).check();
  await expect(page.getByText('1 of 1 preparation items complete', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit checklist item Prepare the welcome pack', exact: true }).click();
  await page.getByLabel('Item owner', { exact: true }).fill('Welcome team');
  await page.getByRole('button', { name: 'Save preparation item', exact: true }).click();
  await expect(page.getByText('Welcome team', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Attendance', exact: true }).click();
  await page.getByLabel(`Attendance for ${volunteer.name}`, { exact: true }).selectOption('attended');
  await expect(page.getByText('1 attended', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: `Edit attendance notes for ${volunteer.name}`, exact: true }).click();
  await page.getByLabel(`Attendance notes for ${volunteer.name}`, { exact: true }).fill('Completed the welcome briefing.');
  await page.getByRole('button', { name: 'Save attendance notes', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save attendance notes', exact: true })).toHaveCount(0);
  await expect(page.locator('.event-attendance-note')).toHaveText('Completed the welcome briefing.');
  await page.getByRole('tab', { name: 'Files & links', exact: true }).click();
  await page.getByRole('button', { name: 'Upload file', exact: true }).click();
  const report = `Event report: ${title}\nOne volunteer attended; orientation complete.`;
  await page.getByLabel('File', { exact: true }).setInputFiles({ name: 'orientation-report.txt', mimeType: 'text/plain', buffer: Buffer.from(report) });
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  const fileDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download orientation-report.txt', exact: true }).click();
  expect(await readFile((await (await fileDownload).path())!, 'utf8')).toBe(report);
  await page.getByRole('button', { name: 'Add link', exact: true }).click();
  await page.getByLabel('Link title', { exact: true }).fill('Shared preparation folder');
  await page.getByLabel('Sharing URL', { exact: true }).fill('https://drive.google.com/drive/folders/example');
  await page.getByRole('button', { name: 'Save link', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Open Shared preparation folder', exact: true })).toHaveAttribute('href', 'https://drive.google.com/drive/folders/example');
  const calendarDownload = page.waitForEvent('download');
  await page.getByRole('dialog').getByRole('button', { name: 'Calendar', exact: true }).click();
  const calendar = await readFile((await (await calendarDownload).path())!, 'utf8');
  expect(calendar).toContain(`SUMMARY:${title}`);
  expect(calendar).toContain('Meeting: https://example.org/meeting/briefing');
  expect(calendar).toContain('STATUS:CONFIRMED');
  const workbookDownload = page.waitForEvent('download');
  await page.getByRole('dialog').getByRole('button', { name: /Excel/ }).click();
  expect((await workbookDownload).suggestedFilename()).toMatch(/\.xlsx$/);
  await page.reload();
  await expect(page.getByRole('dialog', { name: title, exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Checklist', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: /Prepare the welcome pack/ })).toBeChecked();
  await page.getByRole('tab', { name: 'Connections', exact: true }).click();
  await page.getByRole('button', { name: new RegExp(`SERVICE SHIFT.*${shift.title}`) }).click();
  await expect(page.getByRole('dialog', { name: 'Review shift & assignments', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: title, exact: true })).toBeVisible();
  const finalState = await (await page.request.get('/api/state')).json();
  const event = finalState.events.find((item: { title: string }) => item.title === title);
  expect(event.checklist[0].done).toBe(true);
  expect(event.checklist[0].owner).toBe('Welcome team');
  expect(event.attendance[0].status).toBe('attended');
  expect(event.attendance[0].notes).toBe('Completed the welcome briefing.');
  expect(finalState.attachments.filter((item: { targetId: string }) => item.targetId === event.id)).toHaveLength(2);
});
