// SPDX-License-Identifier: AGPL-3.0-only
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('custom profile fields, contact details, dated records and their files persist together',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Explore demo workspace'}).click();
  await page.getByRole('navigation').getByRole('button',{name:'Volunteers',exact:true}).click();
  const label=`Review score ${Date.now()}`;
  await page.getByRole('button',{name:'Customize records',exact:true}).click();
  await page.getByRole('button',{name:'Add field',exact:true}).click();
  await page.getByLabel('Field label',{exact:true}).fill(label);
  await page.getByLabel('Field type',{exact:true}).selectOption('number');
  await page.getByRole('button',{name:'Save field',exact:true}).click();
  await expect(page.getByText(label,{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  const before=await(await page.request.get('/api/state')).json();const volunteer=before.volunteers[0];
  await page.getByRole('button',{name:`View ${volunteer.name}`,exact:true}).click();
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByLabel('Preferred contact',{exact:true}).selectOption('phone');
  await page.getByLabel('Profile tags',{exact:true}).fill('Team mentor, Thursday group');
  await page.getByLabel('Emergency contact name',{exact:true}).fill('Fictional support contact');
  await page.getByLabel('Emergency contact phone',{exact:true}).fill('0300001234');
  await page.getByLabel(label,{exact:true}).fill('0');
  await page.getByRole('button',{name:'Save volunteer',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto(`/#/volunteers?id=${volunteer.id}`);await page.reload();
  await expect(page.getByRole('dialog',{name:'Volunteer profile'})).toBeVisible();
  await expect(page.getByText('Fictional support contact',{exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Records',exact:true}).click();
  await page.getByRole('button',{name:'Add record',exact:true}).click();
  const title=`Mentoring milestone ${Date.now()}`;
  await page.getByLabel('Record title',{exact:true}).fill(title);
  await page.getByLabel('Record category',{exact:true}).fill('Mentoring review');
  await page.getByLabel('Record details',{exact:true}).fill('Reviewed the orientation checklist with the coordinator.');
  await page.getByRole('button',{name:'Save record',exact:true}).click();
  const entry=page.locator('.journal-entry').filter({has:page.getByRole('heading',{name:title,exact:true})});
  await expect(entry).toBeVisible();
  await entry.getByRole('button',{name:'Upload file',exact:true}).click();
  const content='SHUORI fictional mentoring report\nChecklist reviewed.';
  await entry.getByLabel('File',{exact:true}).setInputFiles({name:'mentoring-report.txt',mimeType:'text/plain',buffer:Buffer.from(content)});
  await entry.getByRole('button',{name:'Upload',exact:true}).click();
  await expect(entry.getByText('mentoring-report.txt',{exact:true})).toBeVisible();
  const downloading=page.waitForEvent('download');
  await entry.getByRole('button',{name:'Download mentoring-report.txt',exact:true}).click();
  const downloaded=await downloading;expect(await readFile((await downloaded.path())!,'utf8')).toBe(content);
  await entry.getByRole('button',{name:'Add link',exact:true}).click();
  await entry.getByLabel('Link title',{exact:true}).fill('Team reporting folder');
  await entry.getByLabel('Sharing URL',{exact:true}).fill('https://drive.google.com/drive/folders/example-folder');
  await entry.getByRole('button',{name:'Save link',exact:true}).click();
  await expect(entry.getByRole('link',{name:'Open Team reporting folder',exact:true})).toHaveAttribute('href','https://drive.google.com/drive/folders/example-folder');
  const state=await(await page.request.get('/api/state')).json();
  const field=state.fieldDefinitions.find((f:any)=>f.label===label);const saved=state.volunteers.find((v:any)=>v.id===volunteer.id);
  expect(saved.customFields[field.id]).toBe(0);expect(saved.tags).toEqual(['Team mentor','Thursday group']);expect(saved.contactPreference).toBe('phone');
  const record=state.entries.find((e:any)=>e.title===title);
  expect(state.attachments.filter((a:any)=>a.targetType==='entries'&&a.targetId===record.id)).toHaveLength(2);
  await page.reload();await page.getByRole('tab',{name:'Records',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
});

test('viewer can inspect record fields and supporting files without editing controls',async({page})=>{
  await page.goto('/');await page.request.post('/api/demo-login',{data:{username:'viewer'}});
  const state=await(await page.request.get('/api/state')).json();
  await page.goto(`/#/volunteers?id=${state.volunteers[0].id}`);await page.reload();
  await expect(page.getByRole('dialog',{name:'Volunteer profile'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Edit profile',exact:true})).toHaveCount(0);
  await page.getByRole('tab',{name:'Records',exact:true}).click();
  await expect(page.getByRole('button',{name:'Add record',exact:true})).toHaveCount(0);
  await page.getByRole('tab',{name:'Files',exact:true}).click();
  await expect(page.getByRole('heading',{name:/Files & shared links/})).toBeVisible();
  await expect(page.getByRole('button',{name:'Upload file',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Add link',exact:true})).toHaveCount(0);
});
