// SPDX-License-Identifier: AGPL-3.0-only
import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';

async function signIn(page: Page) {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore demo workspace' }).click();
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();
}
async function go(page: Page, name: string) {
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name, exact: true }).click();
}
const unique = (prefix: string) => `${prefix} ${Date.now()}`;

test('volunteer onboarding edits persist with availability and administrative readiness', async ({ page }) => {
  await signIn(page);
  await go(page, 'Volunteers');
  const name = unique('Review Volunteer');
  await page.getByRole('button', { name: 'Add volunteer', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Close dialog', exact: true })).toBeFocused();
  await page.getByRole('textbox', { name: 'Full name', exact: true }).pressSequentially(name, { delay: 30 });
  await expect(page.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue(name);
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('coordinator-review@example.invalid');
  await page.getByRole('combobox', { name: 'Programme status' }).selectOption('active');
  await page.getByRole('textbox', { name: 'Skills', exact: true }).fill('Wayfinding, Library support');
  await page.getByRole('textbox', { name: 'Languages', exact: true }).fill('Japanese, English');
  await page.getByRole('combobox', { name: 'Training status', exact: true }).selectOption('complete');
  await page.getByRole('combobox', { name: 'Health administration status' }).selectOption('cleared');
  const reviewDate = new Date(`${await page.getByLabel('Workspace date', { exact: true }).inputValue()}T12:00:00Z`);
  reviewDate.setUTCFullYear(reviewDate.getUTCFullYear() + 1);
  await page.getByLabel('Next clearance review', { exact: true }).fill(reviewDate.toISOString().slice(0, 10));
  await page.getByLabel('Maximum hours per week', { exact: true }).fill('10');
  await page.getByRole('checkbox', { name: 'Fri', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Save volunteer', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('textbox', { name: 'Search volunteers' }).fill(name);
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button', { name: `View ${name}`, exact: true }).click();
  await expect(page.getByText('10h maximum per week', { exact: false })).toBeVisible();
  await page.getByRole('tab', { name: 'Eligibility', exact: true }).click();
  await expect(page.getByText('Ready for compatible shifts', { exact: true })).toBeVisible();
  const state = await (await page.request.get('/api/state')).json();
  const saved = state.volunteers.find((v: any) => v.name === name);
  expect(saved.availability).toEqual(['mon', 'tue', 'wed', 'thu']);
  expect(saved.skills).toEqual(['Wayfinding', 'Library support']);
  expect(saved.healthStatus).toBe('cleared');
  expect(saved.maxHoursPerWeek).toBe(10);
});

test('record correction survives reload and updates the monthly report and CSV', async ({ page }) => {
  await signIn(page);
  await go(page, 'Activity records');
  await page.getByRole('button', { name: 'All dates', exact: true }).click();
  const notes = unique('Verified participation correction');
  await page.locator('tbody tr').first().getByRole('button', { name: /Edit record for/ }).click();
  await page.getByLabel('Actual hours', { exact: true }).fill('1.25');
  await page.getByLabel('Service interactions', { exact: true }).fill('37');
  await page.getByRole('textbox', { name: 'Activity notes' }).fill(notes);
  const response = page.waitForResponse(r => r.url().includes('/api/records/') && r.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save activity', exact: true }).click();
  const saved = await (await response).json();
  expect(saved.hours).toBe(1.25);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: 'All dates', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search activity records' }).fill(notes);
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody tr').getByText('1.3 h', { exact: true })).toBeVisible();
  const state = await (await page.request.get('/api/state')).json();
  expect(state.records.find((r: any) => r.id === saved.id).serviceCount).toBe(37);
  const month = saved.date.slice(0, 7);
  const total = state.records.filter((r: any) => r.date.startsWith(month)).reduce((sum: number, r: any) => sum + r.hours, 0);
  await go(page, 'Reports & insights');
  await page.getByLabel('Reporting period', { exact: true }).fill(month);
  await expect(page.locator('.op-stat').filter({ has: page.getByText('Volunteer hours', { exact: true }) }).locator('strong')).toHaveText(total.toFixed(1));
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click();
  const download = await downloadEvent;
  const csv = await readFile((await download.path())!, 'utf8');
  expect(csv).toContain('Recorded hours');
  expect(csv).toContain(month);
  expect(download.suggestedFilename()).toBe(`volunteer-monthly-report-${month}.csv`);
});

test('support resolutions require an outcome and remain in the resolved column', async ({ page }) => {
  await signIn(page);
  await go(page, 'Support & improvement');
  const title = unique('Wayfinding review');
  await page.getByRole('button', { name: 'New request', exact: true }).click();
  await page.getByRole('textbox', { name: 'Request title', exact: true }).fill(title);
  await page.getByRole('combobox', { name: 'Category', exact: true }).selectOption('improvement');
  await page.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('high');
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('Review the welcome card with the reception coordinator.');
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('resolved');
  await page.getByRole('button', { name: 'Save resolution', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  expect(await page.getByRole('textbox', { name: 'Resolution (required)' }).evaluate((el: HTMLTextAreaElement) => el.validity.valueMissing)).toBe(true);
  await page.getByRole('textbox', { name: 'Resolution (required)' }).fill('Reception team reviewed and approved the revised wording.');
  await page.getByRole('button', { name: 'Save resolution', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('textbox', { name: 'Search support requests' }).fill(title);
  await expect(page.getByRole('region', { name: 'Resolved requests', exact: true }).getByRole('button', { name: new RegExp(title) })).toBeVisible();
  await page.getByRole('region', { name: 'Resolved requests', exact: true }).getByRole('button').click();
  await expect(page.getByText('Reception team reviewed and approved the revised wording.', { exact: true })).toBeVisible();
  const state = await (await page.request.get('/api/state')).json();
  const saved = state.requests.find((r: any) => r.title === title);
  expect(saved.status).toBe('resolved');
  expect(saved.dueDate).toBe('');
});

test('resource availability validates quantity, maintenance removes capacity, and deletion persists', async ({ page }) => {
  await signIn(page);
  await go(page, 'Resources');
  const name = unique('Review mobility supplies');
  await page.getByRole('button', { name: 'Add resource', exact: true }).click();
  await page.getByRole('textbox', { name: 'Resource name', exact: true }).fill(name);
  await page.getByLabel('Total quantity', { exact: true }).fill('4');
  await page.getByLabel('Available quantity', { exact: true }).fill('5');
  await page.getByRole('button', { name: 'Save resource', exact: true }).click();
  expect(await page.getByLabel('Available quantity', { exact: true }).evaluate((el: HTMLInputElement) => el.validity.rangeOverflow)).toBe(true);
  await page.getByLabel('Available quantity', { exact: true }).fill('3');
  await page.getByRole('button', { name: 'Save resource', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('textbox', { name: 'Search resources' }).fill(name);
  await page.getByRole('button', { name, exact: true }).click();
  await expect(page.getByText('3 / 4', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Update resource', exact: true }).click();
  await page.getByRole('combobox', { name: 'Condition', exact: true }).selectOption('maintenance');
  await expect(page.getByLabel('Available quantity', { exact: true })).toHaveValue('0');
  await page.getByRole('button', { name: 'Save resource', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const state = await (await page.request.get('/api/state')).json();
  expect(state.resources.find((r: any) => r.name === name).available).toBe(0);
  await page.getByRole('button', { name, exact: true }).click();
  await page.getByRole('button', { name: 'Remove', exact: true }).click();
  await page.getByRole('button', { name: 'Remove resource', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('textbox', { name: 'Search resources' }).fill(name);
  await expect(page.getByRole('heading', { name: 'No resources match' })).toBeVisible();
  const after = await (await page.request.get('/api/state')).json();
  expect(after.resources.some((r: any) => r.name === name)).toBe(false);
  expect(after.audit.some((a: any) => a.action === 'delete' && a.summary.includes(name))).toBe(true);
});

test('administrator creates and changes account roles and downloads a credential-free backup', async ({ page }) => {
  await signIn(page);
  await go(page, 'Workspace settings');
  await page.getByRole('tab', { name: 'Access & accounts', exact: true }).click();
  const name = unique('Operations reviewer');
  const username = `reviewer-${Date.now()}`;
  await page.getByRole('button', { name: 'Add account', exact: true }).click();
  await page.getByRole('textbox', { name: 'Account holder name', exact: true }).fill(name);
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill(username);
  await page.getByLabel('Initial password', { exact: true }).fill('Testing-Workspace-42!');
  await page.getByRole('button', { name: 'Save account', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const row = page.locator('tbody tr').filter({ hasText: username });
  await expect(row).toHaveCount(1);
  await row.getByRole('button', { name: 'Edit', exact: false }).click();
  await page.getByRole('combobox', { name: 'Access role', exact: true }).selectOption('viewer');
  await page.getByRole('button', { name: 'Save account', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(row.getByText('viewer', { exact: true })).toBeVisible();
  const users = await (await page.request.get('/api/users')).json();
  expect(users.find((u: any) => u.username === username).role).toBe('viewer');
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download backup', exact: true }).click();
  const download = await downloadEvent;
  const backupText = await readFile((await download.path())!, 'utf8');
  const backup = JSON.parse(backupText);
  expect(backup.format).toBe('shuori-backup');
  expect(backup.schemaVersion).toBe(1);
  expect(backup.users.some((u: any) => u.username === username)).toBe(true);
  expect(backup.state.audit.length).toBeGreaterThan(0);
  expect(backupText).not.toContain('password_hash');
  expect(backupText).not.toContain('Testing-Workspace-42!');
  expect(backup).not.toHaveProperty('sessions');
});

test('viewer can inspect operations but cannot mutate or access backup and account administration', async ({ page }) => {
  const login = await page.request.post('/api/demo-login', { data: { username: 'viewer' } });
  expect(login.ok()).toBe(true);
  const session = await login.json();
  await page.goto('/');
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();
  await go(page, 'Volunteers');
  await expect(page.getByRole('button', { name: 'Add volunteer', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: /^View / }).first().click();
  await expect(page.getByRole('button', { name: 'Edit profile', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await go(page, 'Activity records');
  await expect(page.getByRole('button', { name: 'Log activity', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /Edit record for/ })).toHaveCount(0);
  await go(page, 'Support & improvement');
  await expect(page.getByRole('button', { name: 'New request', exact: true })).toHaveCount(0);
  await go(page, 'Resources');
  await expect(page.getByRole('button', { name: 'Add resource', exact: true })).toHaveCount(0);
  await go(page, 'Workspace settings');
  await expect(page.getByRole('tab', { name: 'Access & accounts', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Download backup', exact: true })).toHaveCount(0);
  const mutation = await page.request.post('/api/volunteers', { headers: { 'X-CSRF-Token': session.csrfToken }, data: { name: 'Denied viewer write' } });
  expect(mutation.status()).toBe(403);
  expect((await page.request.get('/api/backup')).status()).toBe(403);
  expect((await page.request.get('/api/users')).status()).toBe(403);
});
