# SPDX-License-Identifier: AGPL-3.0-only
# Public fictional-data demo. Start the tmux app on 127.0.0.1:3001 with
# APP_MODE=demo, TRUST_PROXY=1 and APP_ORIGIN=http://YOUR_SERVER_IP.
server {
    listen 80 default_server;
    server_name _;
    client_max_body_size 16m;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_types text/css text/javascript application/javascript application/json image/svg+xml;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }
}
