// SPDX-License-Identifier: AGPL-3.0-only
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowRight, CalendarDays, CheckSquare2, Clock3, Files, Plus, Search, Settings2, SlidersHorizontal, Users, Video } from 'lucide-react';
import { saveEntity } from '../api';
import type { EventType, PageProps } from '../types';
import { Badge, EmptyState, Field, Modal, PageHeader, formatDate, statusLabel } from '../components/UI';
import EventWorkspace, { EVENT_MODULES, EventForm, eventTone } from '../components/EventWorkspace';
import ExcelExportButton from '../components/ExcelExportButton';
import ViewExportButton from '../components/ViewExportDialog';
import { downloadEventCalendar } from '../event-calendar';
import { CustomFieldManager } from '../components/CustomFields';
import '../events.css';

function TypeManager({ data, refresh, notify, onClose }: PageProps & { onClose: () => void }) {
  const blank: EventType = { id: '', version: 0, name: '', description: '', color: 'blue', defaultModules: [], active: true };
  const [value, setValue] = useState<EventType>(blank); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await saveEntity('eventTypes', value); await refresh(); notify('Event type saved.'); setValue(blank); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Your event types" onClose={() => !busy && onClose()} wide><p className="muted small">Shape events around how your team works. Default tools apply to newly created events; existing events keep their own configuration.</p><div className="event-type-manager"><div className="event-type-list"><button className={`event-type-choice ${!value.id ? 'active' : ''}`} onClick={() => { setValue(blank); setError(''); }}><Plus size={17} /><strong>Create a type</strong></button>{data.eventTypes.map(type => <button key={type.id} className={`event-type-choice ${value.id === type.id ? 'active' : ''}`} onClick={() => { setValue(structuredClone(type)); setError(''); }}><span className={`event-color-dot ${type.color}`} /><span><strong>{type.name}</strong><small>{type.active ? `${data.events.filter(event => event.typeId === type.id).length} events` : 'Retired'}</small></span></button>)}</div><form onSubmit={submit}><fieldset disabled={busy} className="plain-fieldset"><Field label="Type name"><input required maxLength={80} value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} placeholder="e.g. Community workshop" /></Field><Field label="Type description"><textarea maxLength={1000} value={value.description} onChange={e => setValue({ ...value, description: e.target.value })} /></Field><Field label="Type colour"><select value={value.color} onChange={e => setValue({ ...value, color: e.target.value as EventType['color'] })}><option value="blue">Water blue</option><option value="green">Leaf green</option><option value="amber">Warm amber</option><option value="purple">Soft purple</option></select></Field><h3>Default tools</h3><div className="event-default-tools">{EVENT_MODULES.map(module => <label className="checkbox-label" key={module.id}><input type="checkbox" checked={value.defaultModules.includes(module.id)} onChange={e => setValue({ ...value, defaultModules: e.target.checked ? [...value.defaultModules, module.id] : value.defaultModules.filter(id => id !== module.id) })} />{module.title}</label>)}</div><label className="checkbox-label"><input type="checkbox" checked={value.active} onChange={e => setValue({ ...value, active: e.target.checked })} />Available for new events</label></fieldset>{error && <p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="button button-primary" disabled={busy}>{busy ? 'Saving…' : 'Save event type'}</button></div></form></div></Modal>;
}

export default function Events(props: PageProps) {
  const { data, date, user, notify } = props;
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [typeId, setTypeId] = useState('all'); const [period, setPeriod] = useState('all');
  const [selected, setSelected] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [types, setTypes] = useState(false); const [fields, setFields] = useState(false); const [page, setPage] = useState(1);
  const canEdit = user.role !== 'viewer';
  useEffect(() => { const read = () => { const query = new URLSearchParams(window.location.hash.split('?')[1] || ''); setSelected(query.get('id')); }; read(); window.addEventListener('hashchange', read); return () => window.removeEventListener('hashchange', read); }, []);
  function open(id: string) { setSelected(id); window.history.replaceState(null, '', `#/events?id=${encodeURIComponent(id)}`); }
  function close() { setSelected(null); window.history.replaceState(null, '', '#/events'); }
  const filtered = data.events.filter(event => (typeId === 'all' || event.typeId === typeId) && (status === 'all' || event.status === status) && (period === 'all' || (period === 'upcoming' ? event.endDate >= date && !['completed', 'cancelled'].includes(event.status) : event.date <= date && event.endDate >= date)) && `${event.title} ${event.description} ${event.owner} ${event.locationText} ${data.eventTypes.find(type => type.id === event.typeId)?.name || ''}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => `${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));
  const totalPages = Math.max(1, Math.ceil(filtered.length / 12)); const currentPage = Math.min(page, totalPages); const visible = filtered.slice((currentPage - 1) * 12, currentPage * 12);
  const upcoming = data.events.filter(event => event.endDate >= date && !['completed', 'cancelled'].includes(event.status)).sort((a, b) => `${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));
  const next = upcoming[0]; const openItems = upcoming.reduce((count, event) => count + (event.modules.includes('checklist') ? event.checklist.filter(item => !item.done).length : 0), 0);
  return <div className="events-page"><PageHeader eyebrow="EVERY PLAN, PERSON & FOLLOW-THROUGH" title="Events & collaboration" description="A workspace for each moment: briefings, training, service activities and the ideas still taking shape." actions={<>{canEdit && <button className="button button-primary" onClick={() => setCreating(true)}><Plus size={16} />New event</button>}</>} />
    <div className="event-command-row"><div className="event-next-card"><span className="event-next-icon"><CalendarDays size={27} /></span><div><span className="section-kicker">NEXT ON THE CALENDAR</span>{next ? <><h2>{next.title}</h2><p>{formatDate(next.date, { weekday: 'short', day: 'numeric', month: 'short' })} · {next.start} JST · {next.owner || 'Owner to be confirmed'}</p></> : <><h2>Make room for what comes next</h2><p>Create an event to bring the plan and people together.</p></>}</div>{next && <button className="icon-button" aria-label={`Open next event: ${next.title}`} onClick={() => open(next.id)}><ArrowRight size={20} /></button>}</div><div className="event-quick-stat"><strong>{upcoming.length}</strong><span>Upcoming events</span><small>From the workspace date</small></div><div className="event-quick-stat"><strong>{openItems}</strong><span>Preparation items</span><small>Still to complete</small></div></div>
    <div className="event-tools-toolbar"><div className="segmented" role="group" aria-label="Event period">{[['all', 'All events'], ['upcoming', 'Upcoming'], ['today', 'On this date']].map(([id, label]) => <button key={id} className={period === id ? 'active' : ''} onClick={() => { setPeriod(id); setPage(1); }}>{label}</button>)}</div><div className="event-toolbar-actions"><ViewExportButton request={{ view: 'event-agenda', eventIds: filtered.map(event => event.id), statuses: status === 'all' ? ['draft', 'confirmed', 'active', 'completed', 'cancelled'] : [status as 'draft' | 'confirmed' | 'active' | 'completed' | 'cancelled'] }} scope={`${filtered.length} matching events across all pages`} notify={notify} /><ExcelExportButton request={{ kind: 'events', ids: filtered.map(event => event.id) }} scope={`${filtered.length} matching events`} notify={notify} /><button className="button button-secondary" onClick={() => downloadEventCalendar(filtered, data.locations)}><ArrowDownToLine size={14} />Calendar</button>{canEdit && <><button className="button button-secondary" onClick={() => setTypes(true)}><Settings2 size={14} />Event types</button><button className="button button-secondary" onClick={() => setFields(true)}><SlidersHorizontal size={14} />Custom fields</button></>}</div></div>
    <div className="event-filters"><div className="event-search"><Search size={17} /><input aria-label="Search events" placeholder="Find an event, owner or place…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div><select aria-label="Filter event type" value={typeId} onChange={e => { setTypeId(e.target.value); setPage(1); }}><option value="all">Every event type</option>{data.eventTypes.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select><select aria-label="Filter event status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">Every status</option>{['draft', 'confirmed', 'active', 'completed', 'cancelled'].map(item => <option key={item} value={item}>{statusLabel(item)}</option>)}</select></div>
    {visible.length ? <div className="event-card-grid">{visible.map(event => { const type = data.eventTypes.find(item => item.id === event.typeId); const checked = event.checklist.filter(item => item.done).length; return <button className={`event-card event-color-${type?.color || 'blue'}`} key={event.id} onClick={() => open(event.id)} aria-label={`Open event ${event.title}`}><div className="event-card-top"><span className={`event-type event-type-${type?.color || 'blue'}`}>{type?.name || 'Event'}</span><Badge tone={eventTone(event.status)}>{statusLabel(event.status)}</Badge></div><div className="event-card-body"><div className="event-date-tile"><span>{formatDate(event.date, { month: 'short' })}</span><strong>{Number(event.date.slice(8))}</strong></div><div><h3>{event.title}</h3><p><Clock3 size={12} />{event.start}–{event.end} JST{event.endDate !== event.date && ` · until ${formatDate(event.endDate)}`}</p><span className="event-card-place">{event.locationText || data.locations.find(location => location.id === event.locationId)?.name || 'Location to be confirmed'}</span></div></div><p className="event-card-description">{event.description || 'Open the event to add the plan, people and preparation.'}</p><div className="event-card-bottom"><span><Users size={13} />{event.volunteerIds.length} people</span><div><span title="Shared files"><Files size={14} /><span className="sr-only">Files available</span></span>{event.modules.includes('meeting') && <span title="Meeting"><Video size={14} /><span className="sr-only">Meeting</span></span>}{event.modules.includes('checklist') && <span title={`${checked} of ${event.checklist.length} checklist items complete`}><CheckSquare2 size={14} />{checked}/{event.checklist.length}</span>}<ArrowRight size={15} /></div></div></button>; })}</div> : <section className="card"><EmptyState title={data.events.length ? 'No events match this view' : 'Give every event its own workspace'} description={data.events.length ? 'Try another type, status or search term.' : 'Start with a meeting, training session or any event type that suits your team.'} action={canEdit && !data.events.length ? <button className="button button-primary" onClick={() => setCreating(true)}><Plus size={15} />New event</button> : undefined} /></section>}
    <div className="event-pagination"><span>{filtered.length} events · {date} workspace date</span><div><button className="button button-secondary" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</button><span>{currentPage} / {totalPages}</span><button className="button button-secondary" disabled={currentPage === totalPages} onClick={() => setPage(currentPage + 1)}>Next</button></div></div>
    {creating && <EventForm {...props} onClose={() => setCreating(false)} onSaved={open} />}{selected && <EventWorkspace {...props} eventId={selected} onClose={close} />}{types && <TypeManager {...props} onClose={() => setTypes(false)} />}{fields && <Modal title="Custom event fields" onClose={() => setFields(false)} wide><CustomFieldManager {...props} scope="events" /></Modal>}
  </div>;
}
