// SPDX-License-Identifier: AGPL-3.0-only
import { useMemo, useState } from 'react';
import { BookOpen, Download, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { deleteEntity, saveEntity } from '../api';
import type { ActivityRecord, PageProps } from '../types';
import { Badge, EmptyState, Field, Modal, PageHeader } from '../components/UI';
import ExcelExportButton from '../components/ExcelExportButton';
import '../operations.css';

const categories=['Reception & guidance','Mobility support','Library services','Events & wellbeing','Training','Administration'];
export function exportCsv(filename:string,headers:string[],rows:(string|number)[][]) {
  const safe=(value:string|number)=>{const s=String(value);return `"${(/^[\s]*[=+@-]|^[\t\r\n]/.test(s)?"'":"")+s.replaceAll('"','""')}"`;};
  const blob=new Blob(['\uFEFF'+[headers,...rows].map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});
  const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),500);
}
export default function Records({data,date,user,refresh,notify}:PageProps) {
  const [search,setSearch]=useState('');const [month,setMonth]=useState(date.slice(0,7));const [category,setCategory]=useState('all');const [page,setPage]=useState(1);
  const [editing,setEditing]=useState<ActivityRecord|null>(null);const [deleting,setDeleting]=useState<ActivityRecord|null>(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const canEdit=user.role!=='viewer';
  const volunteerName=(id:string)=>data.volunteers.find(v=>v.id===id)?.name||'Unknown volunteer';const shiftName=(id:string)=>data.shifts.find(s=>s.id===id)?.title||'Unlinked activity';
  const filtered=useMemo(()=>data.records.filter(r=>(!month||r.date.startsWith(month))&&(category==='all'||r.category===category)&&`${volunteerName(r.volunteerId)} ${shiftName(r.shiftId)} ${r.notes}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)),[data.records,data.volunteers,data.shifts,month,category,search]);
  const pages=Math.max(1,Math.ceil(filtered.length/12));const actualPage=Math.min(page,pages);const visible=filtered.slice((actualPage-1)*12,actualPage*12);
  const compatibleShifts=editing?data.shifts.filter(s=>s.volunteerIds.includes(editing.volunteerId)&&s.status!=='cancelled'&&s.date<=date):[];
  function startEdit(record?:ActivityRecord) {setError('');setEditing(record?{...record}:{id:'',version:0,volunteerId:'',shiftId:'',date,hours:0,serviceCount:0,category:categories[0],notes:''});}
  function update<K extends keyof ActivityRecord>(key:K,value:ActivityRecord[K]) {setEditing(r=>r?{...r,[key]:value}:null);}
  function chooseShift(id:string) {const shift=data.shifts.find(s=>s.id===id);if(!shift)return;const hours=(Number(shift.end.slice(0,2))*60+Number(shift.end.slice(3))-Number(shift.start.slice(0,2))*60-Number(shift.start.slice(3)))/60;setEditing(r=>r?{...r,shiftId:id,date:shift.date,hours:Math.max(0,hours)}:null);}
  async function submit(e:React.FormEvent) {e.preventDefault();if(!editing)return;setSaving(true);setError('');try {if(editing.date>date)throw new Error('Activity records cannot be dated in the future.');const shift=data.shifts.find(s=>s.id===editing.shiftId);if(!shift||!shift.volunteerIds.includes(editing.volunteerId))throw new Error('Select a shift assigned to this volunteer.');if(editing.date!==shift.date)throw new Error('The activity date must match its linked shift.');await saveEntity('records',editing);await refresh();setEditing(null);notify('Activity record saved.');}catch(e){const message=e instanceof Error?e.message:'Could not save activity.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  async function remove() {if(!deleting)return;setSaving(true);setError('');try{await deleteEntity('records',deleting);await refresh();setDeleting(null);notify('Activity record deleted.');}catch(e){const message=e instanceof Error?e.message:'Could not delete record.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  function download(){exportCsv(`activity-records-${month||'all'}.csv`,['Date','Volunteer','Shift','Category','Hours','Service interactions','Notes'],filtered.map(r=>[r.date,volunteerName(r.volunteerId),shiftName(r.shiftId),r.category,r.hours,r.serviceCount,r.notes]));notify(`${filtered.length} activity records exported.`);}
  return <><PageHeader eyebrow="PARTICIPATION & IMPACT" title="Activity records" description="A considered record of the time and care your team gives." actions={<><ExcelExportButton request={{kind:'records',ids:filtered.map(value=>value.id)}} scope={`All ${filtered.length} matching records`} notify={notify}/><button className="button button-secondary" onClick={download}><Download size={15}/> Export CSV</button>{canEdit&&<button className="button button-primary" onClick={()=>startEdit()}><Plus size={16}/> Log activity</button>}</>}/>
  <div className="op-stats"><div className="card op-stat"><span>Recorded hours</span><strong>{filtered.reduce((sum,r)=>sum+r.hours,0).toFixed(1)}</strong><small>Within the current filters</small></div><div className="card op-stat"><span>Service interactions</span><strong>{filtered.reduce((sum,r)=>sum+r.serviceCount,0).toLocaleString()}</strong><small>Reported, non-unique interactions</small></div><div className="card op-stat"><span>Participating volunteers</span><strong>{new Set(filtered.map(r=>r.volunteerId)).size}</strong><small>With at least one activity record</small></div><div className="card op-stat"><span>Activity entries</span><strong>{filtered.length}</strong><small>One record per volunteer and shift</small></div></div>
  <div className="op-filters"><div className="op-search"><Search size={16}/><input className="input" aria-label="Search activity records" placeholder="Search volunteer, shift or notes…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><input type="month" className="input" style={{width:165}} aria-label="Activity month" value={month} onChange={e=>{setMonth(e.target.value);setPage(1);}}/><select className="input" aria-label="Activity category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="all">All categories</option>{[...new Set([...categories,...data.records.map(r=>r.category)])].map(c=><option key={c}>{c}</option>)}</select>{month&&<button className="button button-ghost op-small-button" onClick={()=>setMonth('')}>All dates</button>}</div>
  <section className="card"><div className="op-panel-head"><div><h2>Service activity log</h2><p>Actual participation, linked to scheduled work</p></div><BookOpen size={19} className="muted"/></div>{visible.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Volunteer & shift</th><th>Category</th><th>Hours</th><th>Interactions</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td className="op-table-number">{new Date(`${r.date}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</td><td><strong className="small">{volunteerName(r.volunteerId)}</strong><div className="op-muted-note">{shiftName(r.shiftId)}</div>{r.notes&&<div className="op-muted-note" style={{maxWidth:310,whiteSpace:'normal'}}>{r.notes}</div>}</td><td><Badge tone="neutral">{r.category}</Badge></td><td className="op-table-number">{r.hours.toFixed(1)} h</td><td className="op-table-number">{r.serviceCount}</td>{canEdit&&<td><div className="op-inline-actions"><button className="button button-ghost op-small-button" aria-label={`Edit record for ${volunteerName(r.volunteerId)} on ${r.date}`} onClick={()=>startEdit(r)}><Pencil size={14}/></button><button className="button button-ghost op-small-button op-danger" aria-label={`Delete record for ${volunteerName(r.volunteerId)} on ${r.date}`} onClick={()=>{setDeleting(r);setError('');}}><Trash2 size={14}/></button></div></td>}</tr>)}</tbody></table></div>:<EmptyState title="No activity records in this view" description="Adjust the filters or log your team's completed work."/>}<div className="op-pagination"><span>{filtered.length?`${(actualPage-1)*12+1}–${Math.min(actualPage*12,filtered.length)} of ${filtered.length} records`:'0 records'}</span><div className="op-inline-actions"><button className="button button-secondary op-small-button" disabled={actualPage===1} onClick={()=>setPage(actualPage-1)}>Previous</button><span>{actualPage} / {pages}</span><button className="button button-secondary op-small-button" disabled={actualPage===pages} onClick={()=>setPage(actualPage+1)}>Next</button></div></div></section>
  {editing&&<Modal title={editing.id?'Edit activity record':'Log volunteer activity'} onClose={()=>!saving&&setEditing(null)} wide><form className="op-form" onSubmit={submit}>{error&&<div className="op-error" role="alert">{error}</div>}<div className="field-grid"><Field label="Volunteer"><select required className="input" aria-label="Volunteer" value={editing.volunteerId} onChange={e=>setEditing({...editing,volunteerId:e.target.value,shiftId:'',hours:0})}><option value="">Select a volunteer</option>{data.volunteers.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Assigned shift" hint="Only non-cancelled shifts on or before today are shown."><select required className="input" aria-label="Assigned shift" value={editing.shiftId} onChange={e=>chooseShift(e.target.value)}><option value="">Select an assigned shift</option>{compatibleShifts.map(s=><option key={s.id} value={s.id}>{s.date} · {s.title} ({s.start}–{s.end})</option>)}</select></Field><Field label="Activity date"><input type="date" required readOnly className="input" aria-label="Activity date" value={editing.date}/></Field><Field label="Service category"><select className="input" aria-label="Service category" value={editing.category} onChange={e=>update('category',e.target.value)}>{[...new Set([...categories,...data.records.map(r=>r.category)])].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Actual hours" hint="Enter actual participation, excluding breaks."><input type="number" min="0.25" max="24" step="0.25" required className="input" aria-label="Actual hours" value={editing.hours} onChange={e=>update('hours',Number(e.target.value))}/></Field><Field label="Service interactions" hint="A count of support interactions, not unique patients."><input type="number" min="0" max="10000" step="1" required className="input" aria-label="Service interactions" value={editing.serviceCount} onChange={e=>update('serviceCount',Number(e.target.value))}/></Field></div>{editing.volunteerId&&!compatibleShifts.length&&<div className="op-notice">This volunteer has no eligible assigned shifts. Add an assignment in Schedule before logging their activity.</div>}<Field label="Activity notes" hint="Describe the work or handover. Do not include patient identifiers."><textarea aria-label="Activity notes" className="input" maxLength={3000} value={editing.notes} onChange={e=>update('notes',e.target.value)}/></Field><div className="form-actions"><button type="button" className="button button-secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" disabled={saving||!editing.shiftId}>{saving?'Saving…':'Save activity'}</button></div></form></Modal>}
  {deleting&&<Modal title="Delete activity record?" onClose={()=>!saving&&setDeleting(null)}>{error&&<div role="alert" className="op-error">{error}</div>}<p className="op-wide-text">Remove the {deleting.hours.toFixed(1)}-hour record for <strong>{volunteerName(deleting.volunteerId)}</strong> on {deleting.date}? This changes report totals. The deletion remains in the audit trail.</p><div className="form-actions"><button className="button button-secondary" disabled={saving} onClick={()=>setDeleting(null)}>Keep record</button><button className="button button-primary op-danger" disabled={saving} onClick={remove}>{saving?'Deleting…':'Delete record'}</button></div></Modal>}
  </>;
}
