// SPDX-License-Identifier: AGPL-3.0-only
import { useMemo, useState } from 'react';
import { ArrowDownToLine, Award, CalendarDays, ChartNoAxesCombined, Printer } from 'lucide-react';
import type { PageProps } from '../types';
import { Badge, EmptyState, PageHeader } from '../components/UI';
import { exportCsv } from './Records';
import ExcelExportButton from '../components/ExcelExportButton';
import ViewExportButton from '../components/ViewExportDialog';
import '../operations.css';

function monthOffset(month:string,delta:number){const [year,m]=month.split('-').map(Number);const d=new Date(Date.UTC(year,m-1+delta,1));return d.toISOString().slice(0,7);}
function monthLabel(month:string,short=false){return new Date(`${month}-01T12:00:00`).toLocaleDateString('en-GB',{month:short?'short':'long',...(!short?{year:'numeric' as const}:{})});}
export default function Reports({data,date,notify}:PageProps) {
  const [month,setMonth]=useState(date.slice(0,7));
  const report=useMemo(()=>{
    const records=data.records.filter(r=>r.date.startsWith(month));const hours=records.reduce((s,r)=>s+r.hours,0);const interactions=records.reduce((s,r)=>s+r.serviceCount,0);const volunteerIds=[...new Set(records.map(r=>r.volunteerId))];
    const shifts=data.shifts.filter(s=>s.date.startsWith(month)&&s.status!=='cancelled');const completed=shifts.filter(s=>s.status==='completed');const recordedShifts=new Set(records.map(r=>r.shiftId));
    const categories=[...new Set(records.map(r=>r.category))].map(category=>({category,hours:records.filter(r=>r.category===category).reduce((s,r)=>s+r.hours,0),interactions:records.filter(r=>r.category===category).reduce((s,r)=>s+r.serviceCount,0)})).sort((a,b)=>b.hours-a.hours);
    const people=volunteerIds.map(id=>({id,name:data.volunteers.find(v=>v.id===id)?.name||'Unknown volunteer',hours:records.filter(r=>r.volunteerId===id).reduce((s,r)=>s+r.hours,0),interactions:records.filter(r=>r.volunteerId===id).reduce((s,r)=>s+r.serviceCount,0),shifts:new Set(records.filter(r=>r.volunteerId===id).map(r=>r.shiftId)).size})).sort((a,b)=>b.hours-a.hours||a.name.localeCompare(b.name));
    const trend=Array.from({length:6},(_,i)=>{const m=monthOffset(month,i-5);return {month:m,hours:data.records.filter(r=>r.date.startsWith(m)).reduce((s,r)=>s+r.hours,0)};});
    const previous=data.records.filter(r=>r.date.startsWith(monthOffset(month,-1))).reduce((s,r)=>s+r.hours,0);
    return {records,hours,interactions,volunteerIds,shifts,completed,recordedShifts,categories,people,trend,previous};
  },[data,month]);
  const maxTrend=Math.max(1,...report.trend.map(t=>t.hours));
  function download(){exportCsv(`volunteer-monthly-report-${month}.csv`,['Month','Volunteer','Recorded hours','Recorded shifts','Service interactions'],report.people.map(p=>[month,p.name,p.hours,p.shifts,p.interactions]));notify(`Monthly volunteer report exported for ${monthLabel(month)}.`);}
  const delta=report.previous?((report.hours-report.previous)/report.previous)*100:null;
  return <><PageHeader eyebrow="INSIGHTS & RECOGNITION" title="The difference we make" description="Turn everyday participation into a clear picture of your programme." actions={<><ViewExportButton request={{view:'weekly-roster',dateFrom:`${month}-01`,dateTo:new Date(new Date(`${monthOffset(month,1)}-01T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10)}} label="Schedule & event views" scope={`${monthLabel(month)} | scheduled activities`} notify={notify}/><ExcelExportButton request={{kind:'monthly-report',month}} label="Monthly report Excel" scope={`${monthLabel(month)} | complete workbook`} notify={notify} className="button button-secondary op-no-print" disabled={!/^\d{4}-\d{2}$/.test(month)}/><button className="button button-secondary op-no-print" onClick={()=>window.print()}><Printer size={15}/> Print report</button><button className="button button-primary op-no-print" onClick={download}><ArrowDownToLine size={16}/> Export CSV</button></>}/>
    <div className="op-filters" style={{marginTop:24}}><CalendarDays size={16} className="muted"/><label htmlFor="report-month" className="small">Reporting period</label><input id="report-month" aria-label="Reporting period" className="input" type="month" value={month} max={date.slice(0,7)} style={{width:178}} onChange={e=>e.target.value&&setMonth(e.target.value)}/><span className="op-muted-note">Recorded activity · Japan Standard Time</span></div><h2 className="op-print-heading">Volunteer programme · {monthLabel(month)}</h2>
    <div className="op-stats"><div className="card op-stat"><span>Volunteer hours</span><strong>{report.hours.toFixed(1)}</strong><small>{delta===null?'No prior-month comparison':`${delta>=0?'+':''}${delta.toFixed(0)}% versus ${monthLabel(monthOffset(month,-1),true)}`}</small></div><div className="card op-stat"><span>Service interactions</span><strong>{report.interactions.toLocaleString()}</strong><small>Reported support interactions</small></div><div className="card op-stat"><span>Participating volunteers</span><strong>{report.volunteerIds.length}</strong><small>{report.volunteerIds.length?`${(report.hours/report.volunteerIds.length).toFixed(1)} average hours per person`:'No participation recorded yet'}</small></div><div className="card op-stat"><span>Completed shifts</span><strong>{report.completed.length}<span style={{fontSize:17,color:'#496879',letterSpacing:0}}> / {report.shifts.length}</span></strong><small>Of non-cancelled shifts this month</small></div></div>
    <div className="op-report-layout"><section className="card"><div className="op-panel-head"><div><h2>Time given, over time</h2><p>Recorded volunteer hours · Last six months</p></div><ChartNoAxesCombined size={18} className="muted"/></div><div className="op-chart-wrap"><div className="op-bars" role="img" aria-label={report.trend.map(t=>`${monthLabel(t.month)}: ${t.hours.toFixed(1)} hours`).join('. ')}>{report.trend.map(t=><div className="op-bar-group" key={t.month}><span className="op-bar-value">{t.hours.toFixed(1)}</span><div className={`op-bar ${t.month===month?'current':''}`} style={{height:`${t.hours/maxTrend*83}%`}}/></div>)}</div><div className="op-bar-labels" aria-hidden="true">{report.trend.map(t=><span key={t.month}>{monthLabel(t.month,true)}</span>)}</div><p className="op-report-foot">{monthLabel(month)} includes {report.records.length} activity records across {report.recordedShifts.size} shifts. Hours reflect submitted records, so recent activity may still be awaiting entry.</p></div></section><section className="card"><div className="op-panel-head"><div><h2>Where the care goes</h2><p>Recorded hours by service category</p></div></div><div className="op-breakdown">{report.categories.length?report.categories.map((c,i)=><div className="op-breakdown-row" key={c.category}><div><span>{c.category}</span><strong style={{fontWeight:500}}>{c.hours.toFixed(1)} h</strong></div><div className="op-breakdown-track" role="meter" aria-label={`${c.category} share of hours`} aria-valuenow={report.hours?Math.round(c.hours/report.hours*100):0} aria-valuemin={0} aria-valuemax={100}><div className="op-breakdown-fill" style={{width:`${report.hours?c.hours/report.hours*100:0}%`,background:['#176b91','#3298b7','#78b9d1','#acc9dc','#bddfe9'][i%5]}}/></div></div>):<EmptyState title="No service activity yet" description="Categories appear once activities are recorded."/>}<p className="op-report-foot">Service interactions are not a count of unique patients or visitors.</p></div></section></div>
    <section className="card"><div className="op-panel-head"><div><h2>Every contribution matters</h2><p>Participation summary · {monthLabel(month)}</p></div><Badge tone="neutral">{report.people.length} volunteers</Badge></div>{report.people.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Volunteer</th><th>Recorded shifts</th><th>Hours contributed</th><th>Service interactions</th><th>Share of hours</th></tr></thead><tbody>{report.people.map((p,i)=><tr key={p.id}><td><div className="op-person"><span className="op-initials" style={{background:i===0?'#e6f7fb':undefined}}>{p.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><strong>{p.name}</strong></div></td><td className="op-table-number">{p.shifts}</td><td className="op-table-number">{p.hours.toFixed(1)} h</td><td className="op-table-number">{p.interactions.toLocaleString()}</td><td><div style={{display:'flex',alignItems:'center',gap:12}}><div className="op-breakdown-track" style={{width:80}}><div className="op-breakdown-fill" style={{width:`${report.hours?p.hours/report.hours*100:0}%`}}/></div><span className="op-muted-note">{report.hours?Math.round(p.hours/report.hours*100):0}%</span></div></td></tr>)}</tbody></table></div>:<EmptyState title="A fresh page for this month" description="Recorded hours and service interactions will appear here as activity is logged."/>}<div className="op-table-note">Sorted by recorded hours. Participation figures support recognition planning and do not assess the quality of a volunteer's contribution.</div></section>
    <div className="op-recognition"><Award size={24}/><div><h3>Make room for appreciation</h3><p>{report.people.length?`${report.people.length} volunteers contributed ${report.hours.toFixed(1)} hours in ${monthLabel(month)}. Use this summary alongside peer feedback and service milestones when planning recognition.`:'As the programme grows, use monthly participation summaries alongside peer feedback to plan thoughtful volunteer recognition.'}</p></div></div>
  </>;
}
