// SPDX-License-Identifier: AGPL-3.0-only
import { useState } from 'react';
import { Accessibility, BookOpen, Boxes, MapPin, PackageCheck, Plus, Search, Wrench } from 'lucide-react';
import { deleteEntity, saveEntity } from '../api';
import type { PageProps, Resource } from '../types';
import { Badge, EmptyState, Field, Modal, PageHeader, Progress } from '../components/UI';
import ExcelExportButton from '../components/ExcelExportButton';
import '../operations.css';

const categories=['Mobility equipment','Library materials','Event supplies','Safety & identification','Stationery','Other'];
export default function Resources({data,date,user,refresh,notify}:PageProps) {
  const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [location,setLocation]=useState('all');const [editing,setEditing]=useState<Resource|null>(null);const [selected,setSelected]=useState<Resource|null>(null);const [deleting,setDeleting]=useState<Resource|null>(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const canEdit=user.role!=='viewer';const locationName=(id:string)=>data.locations.find(l=>l.id===id)?.name||'Unassigned location';
  const filtered=data.resources.filter(r=>(status==='all'||r.status===status)&&(location==='all'||r.locationId===location)&&`${r.name} ${r.category} ${r.notes}`.toLowerCase().includes(search.toLowerCase()));
  const total=data.resources.reduce((s,r)=>s+r.quantity,0);const available=data.resources.filter(r=>r.status==='ready').reduce((s,r)=>s+r.available,0);
  function startEdit(r?:Resource){setSelected(null);setError('');setEditing(r?{...r}:{id:'',version:0,name:'',category:categories[0],locationId:data.locations[0]?.id||'',quantity:1,available:1,inspectedDate:date,status:'ready',notes:''});}
  function update<K extends keyof Resource>(key:K,value:Resource[K]){setEditing(r=>r?{...r,[key]:value}:null);}
  async function submit(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);setError('');try{if(editing.available>editing.quantity)throw new Error('Available quantity cannot exceed the total quantity.');if(editing.inspectedDate>date)throw new Error('Last inspection cannot be in the future.');await saveEntity('resources',editing);await refresh();setEditing(null);notify('Resource inventory updated.');}catch(e){const message=e instanceof Error?e.message:'Could not save resource.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  async function remove(){if(!deleting)return;setSaving(true);setError('');try{await deleteEntity('resources',deleting);await refresh();setDeleting(null);notify('Resource removed from inventory.');}catch(e){const message=e instanceof Error?e.message:'Could not delete resource.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  return <><PageHeader eyebrow="ENVIRONMENT & EQUIPMENT" title="Ready to help" description="Keep the spaces and supplies behind every service in good order." actions={<><ExcelExportButton request={{kind:'resources',ids:filtered.map(value=>value.id)}} scope={`${filtered.length} filtered resources`} notify={notify}/>{canEdit&&<button className="button button-primary" onClick={()=>startEdit()}><Plus size={16}/> Add resource</button>}</>}/><div className="op-stats"><div className="card op-stat"><span>Resource groups</span><strong>{data.resources.length}</strong><small>Tracked inventory entries</small></div><div className="card op-stat"><span>Total units</span><strong>{total}</strong><small>Across service locations</small></div><div className="card op-stat"><span>Available for use</span><strong>{available}</strong><small>In ready resource groups</small></div><div className="card op-stat"><span>Under maintenance</span><strong>{data.resources.filter(r=>r.status==='maintenance').length}</strong><small>Resource groups awaiting attention</small></div></div>
    <div className="op-filters"><div className="op-search"><Search size={16}/><input className="input" aria-label="Search resources" placeholder="Search equipment, supplies or materials…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input" aria-label="Resource status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All conditions</option><option value="ready">Ready for use</option><option value="maintenance">Maintenance</option></select><select className="input" aria-label="Resource location" value={location} onChange={e=>setLocation(e.target.value)}><option value="all">All locations</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>
    {filtered.length?<div className="op-resource-grid">{filtered.map(r=>{const Icon=/mobility|wheelchair/i.test(r.category+' '+r.name)?Accessibility:/library|book/i.test(r.category+' '+r.name)?BookOpen:Boxes;return <article className="card op-resource-card" key={r.id}><div className="op-resource-top"><div className="op-resource-icon"><Icon size={21}/></div><Badge tone={r.status==='ready'?'green':'amber'}>{r.status==='ready'?'Ready for use':'Maintenance'}</Badge></div><h3><button className="op-link" onClick={()=>setSelected(r)}>{r.name}</button></h3><div className="op-resource-location"><MapPin size={11}/>{locationName(r.locationId)}</div><div className="op-resource-count"><strong>{r.status==='ready'?r.available:0}</strong><span>/ {r.quantity} available</span></div><Progress value={r.quantity?100*(r.status==='ready'?r.available:0)/r.quantity:0} tone={r.status==='maintenance'?'amber':'green'}/><div className="op-resource-footer"><span>{r.inspectedDate?`Checked ${new Date(`${r.inspectedDate}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}`:'Inspection not recorded'}</span><button className="button button-ghost op-small-button" onClick={()=>setSelected(r)}>View details</button></div></article>;})}</div>:<div className="card"><EmptyState title="No resources match" description="Adjust your filters or add the equipment your team uses."/></div>}
    <div className="op-recognition"><PackageCheck size={23}/><div><h3>A well-prepared environment makes a difference.</h3><p>Availability is a coordinator-maintained snapshot. Verify equipment at the service point before each activity and record inspections after checking.</p></div></div>
    {selected&&<Modal title="Resource details" onClose={()=>setSelected(null)}><div className="op-resource-top"><h3 style={{fontSize:22,fontWeight:500,margin:'0 0 15px'}}>{selected.name}</h3><Badge tone={selected.status==='ready'?'green':'amber'}>{selected.status}</Badge></div><dl className="op-detail-grid"><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Location</dt><dd>{locationName(selected.locationId)}</dd></div><div><dt>Available / total units</dt><dd>{selected.status==='ready'?selected.available:0} / {selected.quantity}</dd></div><div><dt>Last inspection</dt><dd>{selected.inspectedDate||'Not recorded'}</dd></div><div className="op-full"><dt>Maintenance & operating notes</dt><dd>{selected.notes||'No notes recorded.'}</dd></div></dl><div className="form-actions">{canEdit&&<button className="button button-ghost op-danger" onClick={()=>{setDeleting(selected);setSelected(null);setError('');}}>Remove</button>}<button className="button button-secondary" onClick={()=>setSelected(null)}>Close</button>{canEdit&&<button className="button button-primary" onClick={()=>startEdit(selected)}>Update resource</button>}</div></Modal>}
    {editing&&<Modal title={editing.id?'Update resource':'Add a resource'} onClose={()=>!saving&&setEditing(null)} wide><form className="op-form" onSubmit={submit}>{error&&<div role="alert" className="op-error">{error}</div>}<Field label="Resource name"><input className="input" aria-label="Resource name" required maxLength={160} value={editing.name} onChange={e=>update('name',e.target.value)}/></Field><div className="field-grid"><Field label="Category"><select className="input" aria-label="Category" value={editing.category} onChange={e=>update('category',e.target.value)}>{[...new Set([...categories,...data.resources.map(r=>r.category)])].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Storage / service location"><select className="input" aria-label="Storage / service location" required value={editing.locationId} onChange={e=>update('locationId',e.target.value)}>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label="Total quantity"><input className="input" aria-label="Total quantity" type="number" min="0" max="100000" step="1" required value={editing.quantity} onChange={e=>update('quantity',Number(e.target.value))}/></Field><Field label="Available quantity"><input className="input" aria-label="Available quantity" disabled={editing.status==='maintenance'} type="number" min="0" max={editing.quantity} step="1" required value={editing.available} onChange={e=>update('available',Number(e.target.value))}/></Field><Field label="Condition"><select className="input" aria-label="Condition" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Resource['status'],available:e.target.value==='maintenance'?0:editing.available})}><option value="ready">Ready for use</option><option value="maintenance">Under maintenance</option></select></Field><Field label="Last inspection date"><input className="input" aria-label="Last inspection date" type="date" max={date} value={editing.inspectedDate} onChange={e=>update('inspectedDate',e.target.value)}/></Field></div>{editing.status==='maintenance'&&<div className="op-notice"><Wrench size={13} style={{verticalAlign:'middle',marginRight:6}}/>This resource group is excluded from ready availability until its condition is changed.</div>}<Field label="Maintenance & operating notes"><textarea className="input" aria-label="Maintenance & operating notes" maxLength={3000} value={editing.notes} onChange={e=>update('notes',e.target.value)}/></Field><div className="form-actions"><button type="button" className="button button-secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving?'Saving…':'Save resource'}</button></div></form></Modal>}
    {deleting&&<Modal title="Remove resource?" onClose={()=>!saving&&setDeleting(null)}>{error&&<div className="op-error" role="alert">{error}</div>}<p className="op-wide-text">Remove <strong>{deleting.name}</strong> from the inventory? Its removal will be recorded in the audit trail.</p><div className="form-actions"><button className="button button-secondary" disabled={saving} onClick={()=>setDeleting(null)}>Keep resource</button><button className="button button-primary op-danger" disabled={saving} onClick={remove}>{saving?'Removing…':'Remove resource'}</button></div></Modal>}
  </>;
}
