// SPDX-License-Identifier: AGPL-3.0-only
import { useState } from 'react';
import { ArrowUpRight, CalendarDays, HeartHandshake, Plus, Search } from 'lucide-react';
import { saveEntity } from '../api';
import type { PageProps, Request } from '../types';
import { Badge, EmptyState, Field, Modal, PageHeader } from '../components/UI';
import ExcelExportButton from '../components/ExcelExportButton';
import '../operations.css';

const statusLabels={open:'Open',in_progress:'In progress',resolved:'Resolved'};
const categoryLabels={consultation:'Volunteer consultation',improvement:'Service improvement',incident:'Incident follow-up',coordination:'Department coordination'};
const statuses:Request['status'][]=['open','in_progress','resolved'];
const categories:Request['category'][]=['consultation','improvement','incident','coordination'];
export default function Support({data,date,user,refresh,notify}:PageProps) {
  const [search,setSearch]=useState('');const [category,setCategory]=useState('all');const [priority,setPriority]=useState('all');const [selected,setSelected]=useState<Request|null>(null);const [editing,setEditing]=useState<Request|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const canEdit=user.role!=='viewer';
  const filtered=data.requests.filter(r=>(category==='all'||r.category===category)&&(priority==='all'||r.priority===priority)&&`${r.title} ${r.description} ${r.owner} ${r.department}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));
  const open=data.requests.filter(r=>r.status!=='resolved');const overdue=open.filter(r=>r.dueDate&&r.dueDate<date);
  function startEdit(r?:Request){setSelected(null);setError('');setEditing(r?{...r}:{id:'',version:0,title:'',category:'consultation',priority:'normal',status:'open',owner:user.name,department:'Medical Services',dueDate:'',description:'',resolution:''});}
  function update<K extends keyof Request>(key:K,value:Request[K]){setEditing(r=>r?{...r,[key]:value}:null);}
  async function submit(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);setError('');try{if(editing.status==='resolved'&&!editing.resolution.trim())throw new Error('Add a resolution note before marking this request resolved.');await saveEntity('requests',editing);await refresh();setEditing(null);notify(editing.status==='resolved'?'Request resolved and recorded.':'Support request saved.');}catch(e){const message=e instanceof Error?e.message:'Could not save request.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  return <><PageHeader eyebrow="SUPPORT & SERVICE IMPROVEMENT" title="Care for the team" description="A shared place to listen, coordinate and make things better." actions={<><ExcelExportButton request={{kind:'requests',ids:filtered.map(value=>value.id)}} scope={`${filtered.length} filtered requests`} notify={notify}/>{canEdit&&<button className="button button-primary" onClick={()=>startEdit()}><Plus size={16}/> New request</button>}</>}/>
    <div className="op-stats"><div className="card op-stat"><span>Open requests</span><strong>{open.length}</strong><small>Awaiting or receiving support</small></div><div className="card op-stat"><span>In progress</span><strong>{data.requests.filter(r=>r.status==='in_progress').length}</strong><small>Actively being coordinated</small></div><div className="card op-stat"><span>High priority</span><strong>{open.filter(r=>r.priority==='high').length}</strong><small>Unresolved items needing attention</small></div><div className="card op-stat"><span>Overdue follow-ups</span><strong>{overdue.length}</strong><small>Follow-up date has passed</small></div></div>
    <div className="op-filters"><div className="op-search"><Search size={16}/><input className="input" aria-label="Search support requests" placeholder="Search requests, owner or department…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input" aria-label="Request category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select><select className="input" aria-label="Request priority" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="high">High priority</option><option value="normal">Normal priority</option><option value="low">Low priority</option></select></div>
    <div className="op-request-grid">{statuses.map(status=><section className="op-request-column" key={status} aria-label={`${statusLabels[status]} requests`}><div className="op-column-heading"><span>{statusLabels[status]}</span><span className="op-column-count">{filtered.filter(r=>r.status===status).length}</span></div>{filtered.filter(r=>r.status===status).map(r=><button className="op-request-card" key={r.id} onClick={()=>setSelected(r)}><div className="op-resource-top"><Badge tone={r.category==='incident'?'amber':r.category==='improvement'?'green':'neutral'}>{r.category}</Badge>{r.priority==='high'?<Badge tone="red">High priority</Badge>:<ArrowUpRight size={14} className="muted"/>}</div><h3>{r.title}</h3><p>{r.description}</p><div className="op-request-meta"><span>{r.department||'No department'}</span><span className={r.dueDate&&r.dueDate<date&&r.status!=='resolved'?'op-overdue':''}>{r.dueDate?<><CalendarDays size={10} style={{verticalAlign:'middle',marginRight:4}}/>{new Date(`${r.dueDate}T12:00:00`).toLocaleDateString('en-GB',{month:'short',day:'numeric'})}</>:'No due date'}</span></div><div style={{borderTop:'1px solid #e5eff5',marginTop:14,paddingTop:12}} className="op-person"><span className="op-initials" style={{width:23,height:23,fontSize:8}}>{r.owner.split(' ').map(w=>w[0]).slice(0,2).join('')||'–'}</span><span style={{fontSize:11,color:'#496879'}}>{r.owner||'Unassigned'}</span></div></button>)}{!filtered.some(r=>r.status===status)&&<div className="op-empty-column"><HeartHandshake size={24} style={{display:'block',margin:'0 auto 12px',opacity:.55}}/>No {statusLabels[status].toLowerCase()} requests in this view.</div>}</section>)}</div>
    <div className="op-muted-note" style={{marginTop:18}}>For administrative follow-up and service improvement. Urgent clinical or safety events must follow the hospital's established escalation process.</div>
    {selected&&<Modal title="Support request" onClose={()=>setSelected(null)} wide><div className="op-chips"><Badge tone={selected.status==='resolved'?'green':selected.status==='in_progress'?'blue':'neutral'}>{statusLabels[selected.status]}</Badge><Badge tone={selected.priority==='high'?'red':'neutral'}>{selected.priority} priority</Badge><Badge tone="neutral">{categoryLabels[selected.category]}</Badge></div><h3 style={{fontWeight:500,fontSize:23,margin:'21px 0 15px'}}>{selected.title}</h3><p className="op-wide-text">{selected.description}</p><dl className="op-detail-grid" style={{margin:'24px 0'}}><div><dt>Coordinator</dt><dd>{selected.owner||'Unassigned'}</dd></div><div><dt>Partner department</dt><dd>{selected.department||'Not specified'}</dd></div><div><dt>Follow-up date</dt><dd>{selected.dueDate||'Not set'} {selected.dueDate&&selected.dueDate<date&&selected.status!=='resolved'&&<Badge tone="amber">Overdue</Badge>}</dd></div><div><dt>Last updated</dt><dd>{selected.updatedAt?new Date(selected.updatedAt).toLocaleDateString('en-GB',{timeZone:'Asia/Tokyo',day:'numeric',month:'short',year:'numeric'}):'Recently added'}</dd></div></dl>{selected.resolution&&<div className="op-notice"><strong>Resolution / follow-up notes</strong><p style={{whiteSpace:'pre-wrap',margin:'8px 0 0'}}>{selected.resolution}</p></div>}<div className="form-actions"><button className="button button-secondary" onClick={()=>setSelected(null)}>Close</button>{canEdit&&<button className="button button-primary" onClick={()=>startEdit(selected)}>Update request</button>}</div></Modal>}
    {editing&&<Modal title={editing.id?'Update support request':'Create support request'} onClose={()=>!saving&&setEditing(null)} wide><form className="op-form" onSubmit={submit}>{error&&<div role="alert" className="op-error">{error}</div>}<Field label="Request title"><input className="input" aria-label="Request title" required maxLength={160} placeholder="What needs attention?" value={editing.title} onChange={e=>update('title',e.target.value)}/></Field><div className="field-grid"><Field label="Category"><select className="input" aria-label="Category" value={editing.category} onChange={e=>update('category',e.target.value as Request['category'])}>{categories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select></Field><Field label="Priority"><select className="input" aria-label="Priority" value={editing.priority} onChange={e=>update('priority',e.target.value as Request['priority'])}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></Field><Field label="Assigned coordinator"><input className="input" aria-label="Assigned coordinator" required value={editing.owner} onChange={e=>update('owner',e.target.value)}/></Field><Field label="Partner department"><input className="input" aria-label="Partner department" value={editing.department} onChange={e=>update('department',e.target.value)}/></Field><Field label="Follow-up date"><input className="input" aria-label="Follow-up date" type="date" value={editing.dueDate} onChange={e=>update('dueDate',e.target.value)}/></Field><Field label="Status"><select className="input" aria-label="Status" value={editing.status} onChange={e=>update('status',e.target.value as Request['status'])}>{statuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field></div><Field label="Description" hint="Describe the administrative need. Exclude patient identifiers and clinical details."><textarea className="input" aria-label="Description" required maxLength={4000} value={editing.description} onChange={e=>update('description',e.target.value)}/></Field><Field label={editing.status==='resolved'?'Resolution (required)':'Follow-up / resolution notes'}><textarea className="input" aria-label={editing.status==='resolved'?'Resolution (required)':'Follow-up / resolution notes'} required={editing.status==='resolved'} maxLength={4000} value={editing.resolution} onChange={e=>update('resolution',e.target.value)}/></Field><div className="form-actions"><button type="button" className="button button-secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving?'Saving…':editing.status==='resolved'?'Save resolution':'Save request'}</button></div></form></Modal>}
  </>;
}
