// SPDX-License-Identifier: AGPL-3.0-only
import { useMemo, useState } from 'react';
import { ArrowUpRight, CheckCircle2, CircleAlert, Mail, Plus, Search, ShieldCheck, Users } from 'lucide-react';
import { saveEntity } from '../api';
import type { PageProps, Volunteer } from '../types';
import { Badge, EmptyState, Field, Modal, PageHeader } from '../components/UI';
import ExcelExportButton from '../components/ExcelExportButton';
import '../operations.css';

const weekdays = [['mon','Mon'],['tue','Tue'],['wed','Wed'],['thu','Thu'],['fri','Fri'],['sat','Sat'],['sun','Sun']];
const initials = (name: string) => name.split(/\s+/).map(s => s[0]).slice(0,2).join('');
const tone = (status: string) => status === 'active' || status === 'complete' || status === 'cleared' ? 'green' : status === 'archived' || status === 'paused' ? 'neutral' : 'amber';
const list = (value: string) => value.split(',').map(s => s.trim()).filter(Boolean);
const fresh = (date: string): Volunteer => ({id:'',version:0,name:'',kana:'',email:'',phone:'',status:'applicant',skills:[],languages:['Japanese'],trainingStatus:'pending',healthStatus:'pending',healthDueDate:'',availability:['mon','tue','wed','thu','fri'],availableFrom:'09:00',availableTo:'16:00',maxHoursPerWeek:12,joinedDate:date,notes:''});

export default function Volunteers({data,date,user,refresh,notify}:PageProps) {
  const [search,setSearch] = useState(''); const [status,setStatus] = useState('all'); const [skill,setSkill] = useState('all');
  const [selected,setSelected] = useState<Volunteer|null>(null); const [tab,setTab] = useState('profile');
  const [editing,setEditing] = useState<Volunteer|null>(null); const [skillsText,setSkillsText] = useState(''); const [languagesText,setLanguagesText] = useState('');
  const [error,setError] = useState(''); const [saving,setSaving] = useState(false);
  const canEdit = user.role !== 'viewer';
  const skills = [...new Set(data.volunteers.flatMap(v=>v.skills))].sort();
  const filtered = useMemo(()=>data.volunteers.filter(v=>(status==='all'||v.status===status)&&(skill==='all'||v.skills.includes(skill))&&`${v.name} ${v.kana} ${v.email} ${v.languages.join(' ')} ${v.skills.join(' ')}`.toLowerCase().includes(search.toLowerCase())),[data.volunteers,search,status,skill]);
  const active = data.volunteers.filter(v=>v.status==='active');
  const ready = active.filter(v=>v.trainingStatus==='complete'&&v.healthStatus==='cleared'&&(!!v.healthDueDate&&v.healthDueDate>=date));
  const needsReview = data.volunteers.filter(v=>v.status!=='archived'&&(v.healthStatus!=='cleared'||v.trainingStatus!=='complete'||(!v.healthDueDate||v.healthDueDate<date)));
  const selectedRecords = selected ? data.records.filter(r=>r.volunteerId===selected.id) : [];
  const selectedShifts = selected ? data.shifts.filter(s=>s.volunteerIds.includes(selected.id)).sort((a,b)=>b.date.localeCompare(a.date)) : [];
  function edit(v:Volunteer) {setEditing({...v,skills:[...v.skills],languages:[...v.languages],availability:[...v.availability]});setSkillsText(v.skills.join(', '));setLanguagesText(v.languages.join(', '));setSelected(null);setError('');}
  async function submit(e:React.FormEvent) {e.preventDefault();if(!editing)return;setSaving(true);setError('');try {if(editing.availableFrom>=editing.availableTo)throw new Error('The availability end time must be after the start time.');if(!editing.availability.length)throw new Error('Select at least one available day.');await saveEntity('volunteers',{...editing,skills:list(skillsText),languages:list(languagesText)});await refresh();setEditing(null);notify(editing.id?'Volunteer profile updated.':'Volunteer added to the roster.');}catch(e){const message=e instanceof Error?e.message:'Could not save volunteer.';setError(message);notify(message,'error');}finally{setSaving(false);}}
  function update<K extends keyof Volunteer>(key:K,value:Volunteer[K]){setEditing(v=>v?{...v,[key]:value}:null);}
  return <>
    <PageHeader eyebrow="PEOPLE & PARTICIPATION" title="Our volunteers" description="Know your team. Support every step of their journey." actions={<><ExcelExportButton request={{kind:'volunteers',ids:filtered.map(value=>value.id),date}} scope={`${filtered.length} filtered volunteers`} notify={notify}/>{canEdit&&<button className="button button-primary" onClick={()=>edit(fresh(date))}><Plus size={16}/> Add volunteer</button>}</>}/>
    <div className="op-stats">
      <div className="card op-stat"><span>Total volunteers</span><strong>{data.volunteers.filter(v=>v.status!=='archived').length}</strong><small>Across the volunteer programme</small></div>
      <div className="card op-stat"><span>Active volunteers</span><strong>{active.length}</strong><small>Currently participating</small></div>
      <div className="card op-stat"><span>Ready for assignment</span><strong>{ready.length}</strong><small>Training and clearance current</small></div>
      <div className="card op-stat"><span>Eligibility follow-up</span><strong>{needsReview.length}</strong><small>Onboarding or review needed</small></div>
    </div>
    <div className="op-filters"><div className="op-search"><Search size={16}/><input className="input" aria-label="Search volunteers" placeholder="Search name, language or skill…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input" aria-label="Filter volunteer status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['applicant','onboarding','active','paused','archived'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select><select className="input" aria-label="Filter volunteer skill" value={skill} onChange={e=>setSkill(e.target.value)}><option value="all">All skills</option>{skills.map(s=><option key={s}>{s}</option>)}</select></div>
    <section className="card"><div className="op-panel-head"><div><h2>Volunteer directory</h2><p>{filtered.length} people · Thoughtful support, together</p></div><Users size={19} className="muted"/></div>
    {filtered.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Volunteer</th><th>Status</th><th>Skills & languages</th><th>Readiness</th><th>Availability</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><button className="op-link op-person" onClick={()=>{setSelected(v);setTab('profile');}}><span className="op-initials">{initials(v.name)}</span><span><strong>{v.name}</strong><small>{v.email||'No email provided'}</small></span></button></td><td><Badge tone={tone(v.status)}>{v.status}</Badge></td><td><div className="op-chips">{v.skills.slice(0,2).map(s=><span className="op-chip" key={s}>{s}</span>)}{v.skills.length>2&&<span className="op-chip">+{v.skills.length-2}</span>}</div><div className="op-muted-note" style={{marginTop:5}}>{v.languages.join(' · ')||'Languages not recorded'}</div></td><td><div className={`op-check ${v.trainingStatus==='complete'?'positive':'warning'}`}>{v.trainingStatus==='complete'?<CheckCircle2 size={13}/>:<CircleAlert size={13}/>}<span>Training {v.trainingStatus==='complete'?'complete':'pending'}</span></div><div className={`op-check ${v.healthStatus==='cleared'&&(!!v.healthDueDate&&v.healthDueDate>=date)?'positive':'warning'}`} style={{marginTop:6}}><ShieldCheck size={13}/><span>{v.healthDueDate&&v.healthDueDate<date?'Clearance review due':v.healthStatus==='cleared'&&v.healthDueDate?'Clearance current':'Clearance follow-up'}</span></div></td><td><div className="small">{v.availability.map(d=>weekdays.find(w=>w[0]===d)?.[1]||d).join(', ')||'Not set'}</div><div className="op-muted-note">{v.availableFrom}–{v.availableTo} · up to {v.maxHoursPerWeek}h/week</div></td><td><button className="button button-ghost op-small-button" aria-label={`View ${v.name}`} onClick={()=>{setSelected(v);setTab('profile');}}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div>:<EmptyState title="No volunteers match" description="Try another name, status or skill."/>}
    <div className="op-table-note">Eligibility records hold administrative status only. Use approved clinical systems for medical information.</div></section>
    {selected&&<Modal title="Volunteer profile" onClose={()=>setSelected(null)} wide><div className="op-detail-head"><span className="op-initials">{initials(selected.name)}</span><div><h3>{selected.name}</h3><p>{selected.kana||'Volunteer programme'} · Joined {selected.joinedDate}</p></div><Badge tone={tone(selected.status)}>{selected.status}</Badge></div><div className="op-tabs" role="tablist" aria-label="Volunteer profile sections">{['profile','eligibility','activity'].map(t=><button role="tab" aria-selected={tab===t} className={`op-tab ${tab===t?'active':''}`} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
      {tab==='profile'&&<dl className="op-detail-grid"><div><dt>Email</dt><dd>{selected.email?<a href={`mailto:${selected.email}`}><Mail size={12}/> {selected.email}</a>:'Not provided'}</dd></div><div><dt>Phone</dt><dd>{selected.phone||'Not provided'}</dd></div><div><dt>Skills</dt><dd>{selected.skills.join(', ')||'None recorded'}</dd></div><div><dt>Languages</dt><dd>{selected.languages.join(', ')||'None recorded'}</dd></div><div><dt>Available days</dt><dd>{selected.availability.map(d=>weekdays.find(w=>w[0]===d)?.[1]||d).join(', ')}</dd></div><div><dt>Available hours</dt><dd>{selected.availableFrom}–{selected.availableTo} · {selected.maxHoursPerWeek}h maximum per week</dd></div><div className="op-full"><dt>Coordinator notes</dt><dd>{selected.notes||'No notes yet.'}</dd></div></dl>}
      {tab==='eligibility'&&<><div className="op-notice">Administrative coordination only. Record completion and follow-up dates; do not enter diagnoses, antibody results or vaccination details.</div><dl className="op-detail-grid" style={{marginTop:24}}><div><dt>Training</dt><dd><Badge tone={tone(selected.trainingStatus)}>{selected.trainingStatus}</Badge></dd></div><div><dt>Health administration</dt><dd><Badge tone={tone(selected.healthStatus)}>{selected.healthStatus==='followup'?'Follow-up required':selected.healthStatus}</Badge></dd></div><div><dt>Next clearance review</dt><dd>{selected.healthDueDate||'No review date set'} {selected.healthDueDate&&selected.healthDueDate<date&&<Badge tone="amber">Overdue</Badge>}</dd></div><div><dt>Assignment eligibility</dt><dd>{ready.some(v=>v.id===selected.id)?'Ready for compatible shifts':'Requires status, training or clearance review'}</dd></div></dl></>}
      {tab==='activity'&&<><div className="op-summary-line"><span>Recorded hours<strong>{selectedRecords.reduce((a,r)=>a+r.hours,0).toFixed(1)}</strong></span><span>Service interactions<strong>{selectedRecords.reduce((a,r)=>a+r.serviceCount,0)}</strong></span><span>Assigned shifts<strong>{selectedShifts.length}</strong></span></div><div className="table-wrap" style={{marginTop:17}}><table className="data-table"><thead><tr><th>Shift</th><th>Date</th><th>Status</th></tr></thead><tbody>{selectedShifts.slice(0,12).map(s=><tr key={s.id}><td>{s.title}</td><td>{s.date}<div className="op-muted-note">{s.start}–{s.end}</div></td><td><Badge tone={s.status==='completed'?'green':'neutral'}>{s.status}</Badge></td></tr>)}</tbody></table>{!selectedShifts.length&&<EmptyState title="No assigned shifts yet" description="Assignments will appear here after scheduling."/>}</div></>}
      <div className="form-actions"><button className="button button-secondary" onClick={()=>setSelected(null)}>Close</button>{canEdit&&<button className="button button-primary" onClick={()=>edit(selected)}>Edit profile</button>}</div>
    </Modal>}
    {editing&&<Modal title={editing.id?'Edit volunteer':'Welcome a new volunteer'} onClose={()=>!saving&&setEditing(null)} wide><form className="op-form" onSubmit={submit}>{error&&<div className="op-error" role="alert">{error}</div>}<div className="field-grid"><Field label="Full name"><input aria-label="Full name" className="input" required maxLength={120} value={editing.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Name reading (optional)"><input aria-label="Name reading (optional)" className="input" value={editing.kana} onChange={e=>update('kana',e.target.value)}/></Field><Field label="Email"><input aria-label="Email" className="input" type="email" value={editing.email} onChange={e=>update('email',e.target.value)}/></Field><Field label="Phone"><input aria-label="Phone" className="input" type="tel" value={editing.phone} onChange={e=>update('phone',e.target.value)}/></Field><Field label="Programme status"><select aria-label="Programme status" className="input" value={editing.status} onChange={e=>update('status',e.target.value as Volunteer['status'])}>{['applicant','onboarding','active','paused','archived'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Joined date"><input aria-label="Joined date" className="input" type="date" required value={editing.joinedDate} onChange={e=>update('joinedDate',e.target.value)}/></Field><Field label="Skills" hint="Separate skills with commas. Match shift requirements."><input aria-label="Skills" className="input" placeholder="Reception, Wayfinding" value={skillsText} onChange={e=>setSkillsText(e.target.value)}/></Field><Field label="Languages" hint="Separate languages with commas."><input aria-label="Languages" className="input" value={languagesText} onChange={e=>setLanguagesText(e.target.value)}/></Field></div>
    <div className="op-form-section"><h3>Availability & eligibility</h3><Field label="Available days"><div className="op-days">{weekdays.map(([key,label])=><label className="op-day" key={key}><input type="checkbox" checked={editing.availability.includes(key)} onChange={e=>update('availability',e.target.checked?[...editing.availability,key]:editing.availability.filter(d=>d!==key))}/>{label}</label>)}</div></Field><div className="field-grid" style={{marginTop:18}}><Field label="Available from"><input aria-label="Available from" className="input" type="time" required value={editing.availableFrom} onChange={e=>update('availableFrom',e.target.value)}/></Field><Field label="Available until"><input aria-label="Available until" className="input" type="time" required value={editing.availableTo} onChange={e=>update('availableTo',e.target.value)}/></Field><Field label="Maximum hours per week"><input aria-label="Maximum hours per week" className="input" type="number" min="1" max="40" required value={editing.maxHoursPerWeek} onChange={e=>update('maxHoursPerWeek',Number(e.target.value))}/></Field><Field label="Training status"><select aria-label="Training status" className="input" value={editing.trainingStatus} onChange={e=>update('trainingStatus',e.target.value as Volunteer['trainingStatus'])}><option value="pending">Pending</option><option value="complete">Complete</option></select></Field><Field label="Health administration status"><select aria-label="Health administration status" className="input" value={editing.healthStatus} onChange={e=>update('healthStatus',e.target.value as Volunteer['healthStatus'])}><option value="pending">Pending</option><option value="cleared">Cleared</option><option value="followup">Follow-up required</option></select></Field><Field label="Next clearance review"><input aria-label="Next clearance review" className="input" type="date" value={editing.healthDueDate} onChange={e=>update('healthDueDate',e.target.value)}/></Field></div></div><Field label="Coordinator notes" hint="Administrative notes only. Do not enter clinical or patient information."><textarea aria-label="Coordinator notes" className="input" maxLength={3000} value={editing.notes} onChange={e=>update('notes',e.target.value)}/></Field><div className="form-actions"><button type="button" className="button button-secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving?'Saving…':'Save volunteer'}</button></div></form></Modal>}
  </>;
}
