// SPDX-License-Identifier: AGPL-3.0-only
import { useRef, useState } from 'react';
import { Download, ExternalLink, FileText, FolderOpen, Link2, Trash2, Upload } from 'lucide-react';
import { api, downloadFile } from '../api';
import type { Attachment, AttachmentTarget, PageProps } from '../types';
import { EmptyState, Field } from './UI';
import '../records-workspace.css';

const maxBytes=10*1024*1024;
const sizeLabel=(bytes:number)=>bytes>=1024*1024?`${(bytes/(1024*1024)).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
export default function AttachmentPanel({targetType,targetId,data,user,refresh,notify}:Pick<PageProps,'data'|'user'|'refresh'|'notify'>&{targetType:AttachmentTarget;targetId:string}) {
  const [mode,setMode]=useState<'file'|'link'|null>(null);const [name,setName]=useState('');const [url,setUrl]=useState('');const [description,setDescription]=useState('');const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [deleting,setDeleting]=useState<string|null>(null);const picker=useRef<HTMLInputElement>(null);
  const attachments=data.attachments.filter(a=>a.targetType===targetType&&a.targetId===targetId).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));const canEdit=user.role!=='viewer';
  function chooseMode(value:'file'|'link'){setMode(value);setError('');setName('');setUrl('');setDescription('');setFile(null);}
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(mode==='file'){if(!file)throw new Error('Choose a file first.');if(file.size>maxBytes)throw new Error('Choose a file no larger than 10 MiB.');if(file.size===0)throw new Error('The selected file is empty.');const query=new URLSearchParams({targetType,targetId,filename:file.name,description});await api<Attachment>(`/attachments/upload?${query}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});}else{const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.username||parsed.password)throw new Error('Use an HTTPS sharing link without embedded credentials.');await api<Attachment>('/attachments/link',{method:'POST',body:JSON.stringify({targetType,targetId,name,url,description})});}await refresh();setMode(null);notify(mode==='file'?'File uploaded.':'Shared link added.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function remove(attachment:Attachment){setBusy(true);setError('');try{await api(`/attachments/${attachment.id}`,{method:'DELETE',body:JSON.stringify({version:attachment.version})});await refresh();setDeleting(null);notify('Attachment removed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="attachment-panel"><div className="record-section-head"><div><h3><FolderOpen size={18}/> Files & shared links <span className="record-count">{attachments.length}</span></h3><p>Reports, meeting materials and supporting documents, kept with this record.</p></div>{canEdit&&!mode&&<div className="op-inline-actions"><button type="button" className="button button-secondary" onClick={()=>chooseMode('link')}><Link2 size={15}/>Add link</button><button type="button" className="button button-primary" onClick={()=>chooseMode('file')}><Upload size={15}/>Upload file</button></div>}</div>
  {error&&<p role="alert" className="form-error">{error}</p>}
  {mode&&<form className="record-inline-form" onSubmit={submit}><h4>{mode==='file'?'Upload supporting file':'Link a shared file or folder'}</h4>{mode==='file'?<Field label="File" hint="Up to 10 MiB: PDF, Word, Excel, PowerPoint, PNG, JPEG, WebP, text or CSV."><input ref={picker} className="input" type="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg,.webp,.txt,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field>:<><Field label="Link title"><input className="input" required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Event reports — shared Drive folder"/></Field><Field label="Sharing URL" hint="Google Drive, Google Docs, SharePoint or another HTTPS document link."><input className="input" type="url" required maxLength={2048} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://drive.google.com/…"/></Field><p className="small muted">The original service controls access. Adding a link here does not change its sharing permissions or copy its contents.</p></>}<Field label="Description (optional)"><textarea className="input" maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="form-actions"><button type="button" className="button button-secondary" disabled={busy} onClick={()=>setMode(null)}>Cancel attachment</button><button className="button button-primary" disabled={busy}>{busy?'Saving…':mode==='file'?'Upload':'Save link'}</button></div></form>}
  {attachments.length?<div className="attachment-list">{attachments.map(a=><article className="attachment-item" key={a.id}><span className="attachment-symbol">{a.kind==='link'?<Link2 size={21}/>:<FileText size={21}/>}</span><div className="attachment-description"><strong>{a.name}</strong><span>{a.kind==='link'?'External document':sizeLabel(a.size)} · {a.uploadedBy} · {(a.createdAt||'').slice(0,10)}</span>{a.description&&<p>{a.description}</p>}{deleting===a.id&&<div className="attachment-confirm"><span>Remove this attachment{a.kind==='link'?' link':''}?</span><button type="button" className="text-button" disabled={busy} onClick={()=>void remove(a)}>Confirm removal</button><button type="button" className="text-button" onClick={()=>setDeleting(null)}>Keep</button></div>}</div><div className="op-inline-actions">{a.kind==='link'?<a className="button button-secondary" href={a.url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${a.name}`}><ExternalLink size={15}/><span>Open</span></a>:<button type="button" className="button button-secondary" onClick={()=>void downloadFile(`/attachments/${a.id}/download`,a.name).catch(e=>notify(e.message,'error'))} aria-label={`Download ${a.name}`}><Download size={15}/><span>Download</span></button>}{canEdit&&<button type="button" className="icon-button" disabled={busy} aria-label={`Remove attachment ${a.name}`} onClick={()=>setDeleting(a.id)}><Trash2 size={16}/></button>}</div></article>)}</div>:!mode&&<EmptyState title="A home for the supporting details" description="Keep a report here, or connect the team's shared folder so everyone can find it."/>}
  <p className="record-footnote">Uploaded files are available to signed-in workspace members. Coordinators and administrators can add or remove them.</p></section>;
}
