// SPDX-License-Identifier: AGPL-3.0-only
import { useState } from 'react';
import { Archive, Pencil, Plus, SlidersHorizontal } from 'lucide-react';
import { saveEntity } from '../api';
import type { CustomValues, FieldDefinition, FieldScope, PageProps } from '../types';
import { Badge, EmptyState, Field } from './UI';
import '../records-workspace.css';

export function CustomFields({scope,definitions,values={},onChange,readOnly=false}: {scope:FieldScope;definitions:FieldDefinition[];values?:CustomValues;onChange?:(values:CustomValues)=>void;readOnly?:boolean}) {
  const fields=definitions.filter(f=>f.scope===scope&&(f.active||values[f.id]!=null)).sort((a,b)=>a.order-b.order||a.label.localeCompare(b.label));
  const update=(id:string,value:string|number|boolean|null)=>onChange?.({...values,[id]:value});
  if(!fields.length)return <p className="small muted">No additional fields configured. Coordinators can add fields in Customize records.</p>;
  return <div className="field-grid custom-fields">{fields.map(f=>{
    const value=values[f.id];const label=`${f.label}${!f.active?' (archived)':''}`;
    if(readOnly||!f.active)return <div className="custom-field-value" key={f.id}><span>{label}</span><strong>{value===null||value===undefined||value===''?'Not recorded':typeof value==='boolean'?(value?'Yes':'No'):String(value)}</strong></div>;
    const common={className:'input',required:f.required,'aria-label':f.label};
    return <Field key={f.id} label={label} hint={f.required?'Required field':undefined}>{f.type==='textarea'?<textarea {...common} maxLength={4000} value={String(value??'')} onChange={e=>update(f.id,e.target.value)}/>:f.type==='select'?<select {...common} value={String(value??'')} onChange={e=>update(f.id,e.target.value)}><option value="">Not recorded</option>{f.options.map(option=><option key={option}>{option}</option>)}</select>:f.type==='boolean'?<select {...common} value={value===true?'true':value===false?'false':''} onChange={e=>update(f.id,e.target.value===''?null:e.target.value==='true')}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select>:<input {...common} type={f.type==='number'?'number':f.type==='date'?'date':'text'} step={f.type==='number'?'any':undefined} maxLength={f.type==='text'?4000:undefined} value={typeof value==='boolean'?'':value??''} onChange={e=>update(f.id,f.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</Field>;
  })}</div>;
}

export function CustomFieldManager({scope,data,user,refresh,notify}:Pick<PageProps,'data'|'user'|'refresh'|'notify'>&{scope:FieldScope}) {
  const [editing,setEditing]=useState<FieldDefinition|null>(null);const [options,setOptions]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const fields=data.fieldDefinitions.filter(f=>f.scope===scope).sort((a,b)=>a.order-b.order||a.label.localeCompare(b.label));
  const canEdit=user.role!=='viewer';
  function edit(field?:FieldDefinition){setEditing(field?{...field}:{id:'',version:0,scope,label:'',type:'text',options:[],required:false,active:true,order:fields.length});setOptions(field?.options.join('\n')||'');setError('');}
  async function submit(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setError('');try{await saveEntity('fieldDefinitions',{...editing,options:editing.type==='select'?options.split('\n').map(x=>x.trim()).filter(Boolean):[]});await refresh();setEditing(null);notify('Record field saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="record-settings"><div className="record-section-head"><div><h3><SlidersHorizontal size={17}/> Customize records</h3><p>Choose the information your team needs. Existing values stay available when a field is archived.</p></div>{canEdit&&!editing&&<button type="button" className="button button-secondary" onClick={()=>edit()}><Plus size={15}/>Add field</button>}</div>
  {editing?<form className="record-inline-form" onSubmit={submit}><h4>{editing.id?'Edit field':'New custom field'}</h4>{error&&<p className="form-error" role="alert">{error}</p>}<div className="field-grid"><Field label="Field label"><input required maxLength={160} className="input" value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/></Field><Field label="Field type"><select className="input" value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as FieldDefinition['type']})}>{(['text','textarea','number','date','select','boolean'] as const).map(t=><option key={t} value={t}>{({text:'Short text',textarea:'Long text',number:'Number',date:'Date',select:'Choice list',boolean:'Yes / no'})[t]}</option>)}</select></Field><Field label="Display order"><input type="number" min={0} max={1000} required className="input" value={editing.order} onChange={e=>setEditing({...editing,order:Number(e.target.value)})}/></Field><Field label="Field status"><select className="input" value={editing.active?'active':'archived'} onChange={e=>setEditing({...editing,active:e.target.value==='active'})}><option value="active">Active</option><option value="archived">Archived</option></select></Field></div>{editing.type==='select'&&<Field label="Choices" hint="One choice per line. Used choices must remain available."><textarea required className="input" value={options} onChange={e=>setOptions(e.target.value)}/></Field>}<label className="checkbox-label"><input type="checkbox" checked={editing.required} onChange={e=>setEditing({...editing,required:e.target.checked})}/> Require this field when a record is saved</label><div className="form-actions"><button type="button" className="button button-secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancel field edit</button><button className="button button-primary" disabled={busy}>{busy?'Saving…':'Save field'}</button></div></form>:fields.length?<div className="record-field-list">{fields.map(f=><div key={f.id}><div><strong>{f.label}</strong><span>{f.type}{f.required?' · Required':''}{!f.active?' · Archived':''}</span></div>{!f.active&&<Archive size={15}/>}<Badge tone={f.active?'blue':'neutral'}>{f.active?'Active':'Archived'}</Badge>{canEdit&&<button type="button" className="icon-button" aria-label={`Edit field ${f.label}`} onClick={()=>edit(f)}><Pencil size={16}/></button>}</div>)}</div>:<EmptyState title="Make these records your own" description="Add contact preferences, qualifications, review dates, outcomes or another field your team uses."/>}</section>;
}
